name: Build and deploy to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build
          rm -rf node_modules
          npm install --omit=dev
          npm prune --production
          npm cache clean --force


      - name: Create deployment package
        run: |
          mkdir deploy-root
          cp host.json package.json deploy-root/
          cp -r node_modules deploy-root/
          cp -r dist/functions/* deploy-root/     # register-seat.js do ROOTu!
          cd deploy-root && zip -r ../deploy.zip . && cd ..


      - name: Check zip size
        run: ls -lh deploy.zip

      - name: Verify structure
        run: |
          unzip -l deploy.zip | grep -E "(host\.json|register-seat\.js)" | head -5

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E6C62F9A5CC24E54AE9F3D741F1CE886 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B40B9F1578864D62AE87AAFB44DCF973 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BA7359258F004FE3B1A7D338A7CBB3F1 }}

      - name: Set Run from Package
        run: |
          az functionapp config appsettings set \
            --resource-group lf-page \
            --name lf-api \
            --settings WEBSITE_RUN_FROM_PACKAGE=1


      - name: Deploy to Azure Functions
        run: |
          az functionapp deployment source config-zip \
            --resource-group lf-page \
            --name lf-api \
            --src deploy.zip
